name: flutter_rating_bar_plus
description: A simple yet fully customizable ratingbar for flutter which also include a rating bar indicator, supporting any fraction of rating.
version: 4.0.2
repository: https://github.com/abdelrahman-atef1/flutter_rating_bar
homepage: https://abdelrahman-atef1.github.io

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=2.5.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  very_good_analysis: ^5.0.0+1
